# Generated by Django 3.2 on 2023-11-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.CharField(default='2010-10-01', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=True),
        ),
    ]
