# Generated by Django 3.2 on 2023-11-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231120_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(),
        ),
    ]
