# Generated by Django 3.2 on 2023-11-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_model',
            name='genres',
            field=models.ManyToManyField(to='movies.Genre', verbose_name='test_movie'),
        ),
    ]
